name: Pandoc

on:
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - '**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive    
    - name: Install texlive
      run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
  
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.9.2.1'
          
    - name: Build
      run: |
       mkdir dist
       pandoc src/journal-paper.md --to pdf --lua-filter=lua-filters/author-info-blocks/author-info-blocks.lua --from markdown+tex_math_single_backslash-autolink_bare_uris --output dist/journal-paper.pdf --self-contained --highlight-style tango --pdf-engine pdflatex --filter /usr/bin/pandoc-citeproc
     
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: dist
