name: Pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: mkdir
      run: |
       mkdir public
       
    - name: Generate PDF with Pandoc
      uses: docker://pandoc/latex:2.16.2
      with:
        args: "--to pdf --lua-filter=lua-filters/author-info-blocks/author-info-blocks.lua --from markdown+tex_math_single_backslash-autolink_bare_uris --output public/journal-paper.pdf --self-contained --highlight-style tango --pdf-engine pdflatex --citeproc src/journal-paper.md"

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: public
